// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/server.proto

package info

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The parameters to Server.Info.
type Request struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Code                 int32             `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Request) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Request) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// The Response to Server.Info.
type Response struct {
	Request              *Request                  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Data                 map[string]*Response_List `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Response) GetData() map[string]*Response_List {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response_List struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_List) Reset()         { *m = Response_List{} }
func (m *Response_List) String() string { return proto.CompactTextString(m) }
func (*Response_List) ProtoMessage()    {}
func (*Response_List) Descriptor() ([]byte, []int) {
	return fileDescriptor_98d161fbd54d4312, []int{1, 0}
}

func (m *Response_List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_List.Unmarshal(m, b)
}
func (m *Response_List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_List.Marshal(b, m, deterministic)
}
func (m *Response_List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_List.Merge(m, src)
}
func (m *Response_List) XXX_Size() int {
	return xxx_messageInfo_Response_List.Size(m)
}
func (m *Response_List) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_List.DiscardUnknown(m)
}

var xxx_messageInfo_Response_List proto.InternalMessageInfo

func (m *Response_List) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "info.Request")
	proto.RegisterMapType((map[string]string)(nil), "info.Request.MetaEntry")
	proto.RegisterType((*Response)(nil), "info.Response")
	proto.RegisterMapType((map[string]*Response_List)(nil), "info.Response.DataEntry")
	proto.RegisterType((*Response_List)(nil), "info.Response.List")
}

func init() { proto.RegisterFile("pb/server.proto", fileDescriptor_98d161fbd54d4312) }

var fileDescriptor_98d161fbd54d4312 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0xe5, 0x64, 0xd3, 0x90, 0x09, 0xa5, 0x68, 0x00, 0x61, 0xad, 0x38, 0x58, 0xb9, 0x10,
	0x42, 0xb3, 0xdb, 0x2e, 0x07, 0x50, 0x05, 0xaa, 0x8a, 0xca, 0x01, 0xa9, 0x48, 0x68, 0x79, 0x02,
	0x37, 0x9d, 0x2e, 0x2b, 0x52, 0xdb, 0xd8, 0x6e, 0x50, 0x84, 0xb8, 0x70, 0xe1, 0x0e, 0x4f, 0xc2,
	0x73, 0x70, 0xe4, 0x15, 0x78, 0x10, 0x64, 0x6f, 0x12, 0x75, 0x01, 0x89, 0xd3, 0xfe, 0x5e, 0x7f,
	0xf3, 0xcf, 0xef, 0xb1, 0x61, 0xc7, 0x9c, 0xe6, 0x8e, 0xec, 0x82, 0x6c, 0x66, 0xac, 0xf6, 0x1a,
	0x93, 0x5a, 0x9d, 0xeb, 0xf4, 0x5e, 0xa5, 0x75, 0x35, 0xa7, 0x5c, 0x9a, 0x3a, 0x97, 0x4a, 0x69,
	0x2f, 0x7d, 0xad, 0x95, 0x6b, 0x98, 0x74, 0x37, 0x7e, 0x66, 0xd3, 0x8a, 0xd4, 0xd4, 0x7d, 0x90,
	0x55, 0x45, 0x36, 0xd7, 0x26, 0x12, 0x7f, 0xd3, 0xa3, 0xef, 0x0c, 0xfa, 0x25, 0xbd, 0xbf, 0x24,
	0xe7, 0x11, 0x21, 0xf1, 0x4b, 0x43, 0x9c, 0x09, 0x36, 0x1e, 0x94, 0x51, 0x23, 0x87, 0xfe, 0x05,
	0x39, 0x27, 0x2b, 0xe2, 0x9d, 0xf8, 0x7b, 0xbd, 0xc4, 0x87, 0x90, 0x5c, 0x90, 0x97, 0xbc, 0x2b,
	0xba, 0xe3, 0x61, 0x71, 0x37, 0x0b, 0xd1, 0xb2, 0x95, 0x55, 0xf6, 0x8a, 0xbc, 0x7c, 0xa1, 0xbc,
	0x5d, 0x96, 0x11, 0x0a, 0xd6, 0x33, 0x7d, 0x46, 0x3c, 0x11, 0x6c, 0xdc, 0x2b, 0xa3, 0x4e, 0x1f,
	0xc3, 0x60, 0x83, 0xe1, 0x4d, 0xe8, 0xbe, 0xa3, 0xe5, 0xaa, 0x75, 0x90, 0x78, 0x1b, 0x7a, 0x0b,
	0x39, 0xbf, 0x5c, 0xf7, 0x6d, 0x16, 0x07, 0x9d, 0x27, 0x6c, 0xf4, 0x83, 0xc1, 0xb5, 0x92, 0x9c,
	0xd1, 0xca, 0x11, 0xde, 0x87, 0xbe, 0x6d, 0x9a, 0x46, 0x70, 0x58, 0x6c, 0xb7, 0x92, 0x94, 0xeb,
	0x5d, 0xdc, 0x85, 0xe4, 0x4c, 0x6e, 0xf2, 0xf2, 0x35, 0xd5, 0xd8, 0x64, 0xc7, 0x72, 0x13, 0x38,
	0x50, 0x69, 0x0a, 0xc9, 0x49, 0xdd, 0xcc, 0x64, 0x5e, 0x3b, 0xcf, 0x99, 0xe8, 0x86, 0x99, 0x04,
	0x9d, 0x9e, 0xc0, 0x60, 0x83, 0xff, 0x23, 0xf8, 0x83, 0xab, 0xc1, 0x87, 0xc5, 0xad, 0x3f, 0x3a,
	0x05, 0xdb, 0x2b, 0xa7, 0x29, 0xbe, 0x30, 0xd8, 0x7a, 0x13, 0x2f, 0x19, 0x9f, 0x42, 0xf2, 0x52,
	0x9d, 0x6b, 0x6c, 0x1f, 0x21, 0xbd, 0xd1, 0x76, 0x18, 0xdd, 0xf9, 0xfc, 0xf3, 0xd7, 0xb7, 0xce,
	0x0e, 0x6e, 0xe7, 0x8b, 0xfd, 0xfc, 0x63, 0xb8, 0xa6, 0x67, 0x93, 0xc9, 0x27, 0x3c, 0x84, 0xe4,
	0xb5, 0x76, 0xfe, 0x7f, 0xd5, 0x3c, 0x56, 0xe3, 0xa8, 0x5d, 0x7d, 0xc0, 0x26, 0xcf, 0x8f, 0xbf,
	0x1e, 0x1d, 0xe1, 0x21, 0x5c, 0x0f, 0xfc, 0x34, 0xbc, 0xbb, 0x7a, 0x46, 0x38, 0x96, 0x62, 0x25,
	0x85, 0xd7, 0xc2, 0xd8, 0x5a, 0x79, 0xf1, 0xd6, 0x7b, 0x23, 0xb4, 0x15, 0x95, 0x35, 0x33, 0xb1,
	0x9a, 0xaf, 0x28, 0x7a, 0xfb, 0xd9, 0x5e, 0xb6, 0x77, 0xba, 0x15, 0x1f, 0xd6, 0xa3, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xf4, 0x9a, 0x05, 0x3d, 0xbd, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	// Get grpc request infos
	Info(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Post
	Post(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Info(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/info.Server/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) Post(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/info.Server/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	// Get grpc request infos
	Info(context.Context, *Request) (*Response, error)
	// Post
	Post(context.Context, *Request) (*Response, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info.Server/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Info(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info.Server/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Post(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Server_Info_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _Server_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/server.proto",
}
