// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/server.proto

package info

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The parameters to Server.Info.
type Request struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_53e4fa34b2ed5363, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// The Response to Server.Info.
type Response struct {
	Data                 map[string]*Response_List `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_53e4fa34b2ed5363, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() map[string]*Response_List {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response_List struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_List) Reset()         { *m = Response_List{} }
func (m *Response_List) String() string { return proto.CompactTextString(m) }
func (*Response_List) ProtoMessage()    {}
func (*Response_List) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_53e4fa34b2ed5363, []int{1, 0}
}
func (m *Response_List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_List.Unmarshal(m, b)
}
func (m *Response_List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_List.Marshal(b, m, deterministic)
}
func (dst *Response_List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_List.Merge(dst, src)
}
func (m *Response_List) XXX_Size() int {
	return xxx_messageInfo_Response_List.Size(m)
}
func (m *Response_List) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_List.DiscardUnknown(m)
}

var xxx_messageInfo_Response_List proto.InternalMessageInfo

func (m *Response_List) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "info.Request")
	proto.RegisterType((*Response)(nil), "info.Response")
	proto.RegisterMapType((map[string]*Response_List)(nil), "info.Response.DataEntry")
	proto.RegisterType((*Response_List)(nil), "info.Response.List")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	// Get grpc request infos
	Info(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Info(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/info.Server/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	// Get grpc request infos
	Info(context.Context, *Request) (*Response, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info.Server/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Info(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Server_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/server.proto",
}

func init() { proto.RegisterFile("pb/server.proto", fileDescriptor_server_53e4fa34b2ed5363) }

var fileDescriptor_server_53e4fa34b2ed5363 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4e, 0x3a, 0x31,
	0x1c, 0xc5, 0xd3, 0x61, 0xe0, 0xf7, 0xa3, 0xa0, 0x92, 0xba, 0x99, 0x4c, 0x34, 0x69, 0x58, 0x8d,
	0x06, 0xa6, 0x30, 0x6e, 0x94, 0x8d, 0xf1, 0xdf, 0xc2, 0x84, 0xd5, 0x78, 0x82, 0x32, 0x96, 0xa1,
	0x32, 0x69, 0x6b, 0x5b, 0x30, 0xc4, 0xb8, 0xf1, 0x08, 0x7a, 0x03, 0xaf, 0xe4, 0x15, 0x3c, 0x88,
	0x99, 0x0e, 0x98, 0x28, 0xab, 0xbe, 0xb4, 0x9f, 0xef, 0x7b, 0xfd, 0x3e, 0xb8, 0xa7, 0x26, 0xc4,
	0x30, 0xbd, 0x64, 0x3a, 0x56, 0x5a, 0x5a, 0x89, 0x7c, 0x2e, 0xa6, 0x32, 0x3c, 0xc8, 0xa5, 0xcc,
	0x0b, 0x46, 0xa8, 0xe2, 0x84, 0x0a, 0x21, 0x2d, 0xb5, 0x5c, 0x0a, 0x53, 0x31, 0x61, 0xcf, 0x1d,
	0x59, 0x3f, 0x67, 0xa2, 0x6f, 0x9e, 0x68, 0x9e, 0x33, 0x4d, 0xa4, 0x72, 0xc4, 0x36, 0xdd, 0x3d,
	0x84, 0xff, 0x52, 0xf6, 0xb8, 0x60, 0xc6, 0x22, 0x04, 0x7d, 0xbb, 0x52, 0x2c, 0x00, 0x18, 0x44,
	0xcd, 0xd4, 0xe9, 0xee, 0x07, 0x80, 0xff, 0x53, 0x66, 0x94, 0x14, 0x86, 0xa1, 0x1e, 0xf4, 0xef,
	0xa9, 0xa5, 0x01, 0xc0, 0xb5, 0xa8, 0x95, 0x04, 0x71, 0xf9, 0x99, 0x78, 0xf3, 0x1a, 0x5f, 0x53,
	0x4b, 0x6f, 0x84, 0xd5, 0xab, 0xd4, 0x51, 0x61, 0x08, 0xfd, 0x31, 0xaf, 0x6c, 0x0b, 0x6e, 0xac,
	0x9b, 0x6a, 0xa6, 0x4e, 0x87, 0x63, 0xd8, 0xfc, 0xc1, 0x51, 0x07, 0xd6, 0xe6, 0x6c, 0xb5, 0x8e,
	0x2d, 0x25, 0x3a, 0x82, 0xf5, 0x25, 0x2d, 0x16, 0x2c, 0xf0, 0x30, 0x88, 0x5a, 0xc9, 0xfe, 0x9f,
	0xa4, 0xd2, 0x36, 0xad, 0x88, 0x91, 0x77, 0x0a, 0x92, 0x2b, 0xd8, 0xb8, 0x73, 0x2d, 0xa1, 0x33,
	0xe8, 0xdf, 0x8a, 0xa9, 0x44, 0x3b, 0x9b, 0x09, 0xb7, 0x59, 0xb8, 0xfb, 0xdb, 0xa0, 0x8b, 0x5e,
	0x3f, 0xbf, 0xde, 0xbd, 0x36, 0x82, 0x64, 0x39, 0x24, 0xcf, 0xe5, 0xa2, 0x2f, 0x97, 0xf3, 0xb7,
	0x8b, 0x19, 0x3a, 0x87, 0xed, 0x92, 0xec, 0x97, 0xa5, 0xf3, 0x8c, 0xa1, 0x88, 0xe2, 0xb5, 0xc4,
	0x56, 0x62, 0xa5, 0xb9, 0xb0, 0x78, 0x66, 0xad, 0xc2, 0x52, 0xe3, 0x5c, 0xab, 0x0c, 0xeb, 0x2a,
	0x01, 0x27, 0xf5, 0x61, 0x3c, 0x88, 0x07, 0xc7, 0xc0, 0x4b, 0x3a, 0x54, 0xa9, 0x82, 0x67, 0xae,
	0x65, 0xf2, 0x60, 0xa4, 0x18, 0x6d, 0xdd, 0x4c, 0x1a, 0xae, 0xfc, 0x93, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd9, 0x2d, 0xcb, 0x3a, 0xe1, 0x01, 0x00, 0x00,
}
